//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuFinanced.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_Notice
    {
        public string N_GUID { get; set; }
        public string N_AdminGUID { get; set; }
        public Nullable<int> N_Category { get; set; }
        public string N_Title { get; set; }
        public string N_Describe { get; set; }
        public Nullable<int> N_Status { get; set; }
        public Nullable<System.DateTime> N_LastTime { get; set; }
    }
}
