//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuFinanced.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_NoticeCategory
    {
        public int NC_ID { get; set; }
        public string NC_Name { get; set; }
        public Nullable<int> NC_ParentID { get; set; }
        public Nullable<int> NC_Level { get; set; }
    }
}
