//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuFinanced.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_AD
    {
        public string AD_GUID { get; set; }
        public string AD_Title { get; set; }
        public string AD_ImgUrl { get; set; }
        public string AD_SeatCode { get; set; }
        public Nullable<bool> AD_Status { get; set; }
    }
}
